version: '3.8'

services:
  deploy:
    container_name: Deploy_nnUNet
    hostname: Deploy_nnUNet
    image: loopbackkr/pytorch:1.11.0-cuda11.3-cudnn8
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}:/workspace
    working_dir: /workspace
    command: python deploy.py